### ISSUE TITLE
is this for xt machine using modern usb keyboard?

### ISSUE THREAD

**Issue by youxiaojie** [mtfurlan/usb-xt-keyboard-converter#1]
1.is this for xt machine using modern usb keyboard?
2.is it possible to support at keyboard such as a jumper?
3.is it support arduino uno? how to wire?
thanks for great project!

**Comment by mtfurlan** [comment]
1. Yes, though it currently has issues like it doesn't do the boot up keyboard check so the coputer will always ask for a keyboard. Also I think it doesn't do some keycodes properly, but I don't really remember.
2. Not yet, but that should be possible.
3. I think I used a teensey, but I don't really remember.
  It needs to be something that can do USB host mode though, so I don't think an uno would work.

I've been meaning to get back to this and clean it up a lot, it was written at Vintage Computer Festival Midwest 2021 and I got it working enough that we had enough keyboards for our table, but I never did the documentation or rewrite I wanted to do.

I'll find the hardware and document the current state when I get home later this month.
If you don't hear anything please keep asking.

**Comment by mtfurlan** [comment]
@youxiaojie I put a readme in, if that doesn't answer your questions reopen this issue.
